export const data = [
  {
    id: 1,
    link: 'https://www.youtube.com/watch?v=6H0Q9QDKRcM',
    title: 'Love In Progress',
    name: 'David Odunayo',
    position: 'Editor | Colourist | Sound',
  },
  {
    id: 2,
    link: 'https://youtu.be/HN-X5xCbNTw?si=V4lpJcQwgkaJWuxh',
    title: 'IMPERFECT MATCH',
    name: 'David Odunayo',
    position: 'Editor | Colourist | Sound',
  },
  {
    id: 3,
    link: 'https://www.youtube.com/watch?v=yLGlclnGJBo',
    title: 'MOMENTS OF TRUTH',
    name: 'David Odunayo',
    position: 'Editor | Colourist | Sound',
  },
  {
    id: 4,
    link: 'https://youtu.be/CR9Ndm6W50g?si=7l-3ZNZEIJDQ8M0E',
    title: 'Heart Over Time',
    name: 'David Odunayo',
    position: 'Editor | Colourist | Sound',
  },
  {
    id: 5,
    link: 'https://youtu.be/wusI_-WUjd4?si=B0sDu1rydxKVU4k4',
    title: 'No Love Lust',
    name: 'David Odunayo',
    position: 'Editor | Colourist | Sound',
  },
  {
    id: 5,
    link: 'https://youtu.be/JzC2bYCV6Jw?si=AygIYmONfu7IlF-l',
    title: 'Dear Diane',
    name: 'David Odunayo',
    position: 'Editor | Colourist | Sound',
  },
  {
    id: 6,
    link: 'https://www.youtube.com/watch?v=kHHCzyqdoNU',
    title: 'Blind Fury',
    name: 'David Odunayo',
    position: 'Editor | Colourist | Sound',
  },
  {
    id: 7,
    link: 'https://www.youtube.com/watch?v=ldOE2aOof58&t=3756s',
    title: 'Sweet Vengeance',
    name: 'David Odunayo',
    position: 'Editor | Colourist | Sound',
  },
  {
    id: 8,
    link: 'https://www.youtube.com/watch?v=pTAheLPUWlw',
    title: 'Summer Rain Official Trailer',
    name: 'David Odunayo',
    position: 'Editor | Colourist | Sound',
  },
  {
    id: 9,
    link: 'https://www.youtube.com/watch?v=NgrN9chjLwo',
    title: 'Official Trailer Of Sisters by Chance',
    name: 'David Odunayo',
    position: 'Editor | Colourist | Sound',
  },
  {
    id: 10,
    link: 'https://www.youtube.com/watch?v=g23mrltsSX4',
    title: 'She ToMy Official Trailer',
    name: 'David Odunayo',
    position: 'Editor',
  },
  {
    id: 10,
    link: 'https://www.youtube.com/watch?v=2tfZEPfnMLI',
    title: 'Trailer of Feeling Butterflies',
    name: 'David Odunayo',
    position: 'Editor | Colourist | Sound',
  },
  {
    id: 11,
    link: 'https://www.youtube.com/watch?v=E1hBB_hA_w8',
    title: 'Trailer of the movie The Kids And The Babysitter',
    name: 'David Odunayo',
    position: 'Editor | Colourist | Sound',
  },
  {
    id: 12,
    link: 'https://www.youtube.com/watch?v=V335_JIzhEU',
    title: 'Two Heartbeats Trailer',
    name: 'David Odunayo',
    position: 'Colourist',
  },
  {
    id: 13,
    link: 'https://www.youtube.com/watch?v=UYsseEOZuDc',
    title: 'Trailer of A Not So Perfect Family',
    name: 'David Odunayo',
    position: 'Editor | Colourist | Sound',
  },
  {
    id: 14,
    link: 'https://www.youtube.com/watch?v=53V3tzH1a-M',
    title: 'Trailer of When Hearts Collide',
    name: 'David Odunayo',
    position: 'Trailer | Colourist | Sound',
  },
  {
    id: 15,
    link: 'https://www.youtube.com/watch?v=kLp6GsmL7fk',
    title: 'Trailer of Moment of Truth',
    name: 'David Odunayo',
    position: 'Editor | Colourist | Sound',
  },
  {
    id: 16,
    link: 'https://www.youtube.com/watch?v=56ma3dYVfM0&t=2171s',
    title: 'Beneath The Facade',
    name: 'David Odunayo',
    position: 'Editor | Colourist | Sound',
  },
  {
    id: 17,
    link: 'https://www.youtube.com/watch?v=D-tudHqBPH0&t=4497s',
    title: 'Brotherly Love',
    name: 'David Odunayo',
    position: 'Editor | Colourist | Sound',
  },
  {
    id: 18,
    link: 'https://www.youtube.com/watch?v=GoWZfsdd1yw&t=5090s',
    title: 'Th Beauty of Things',
    name: 'David Odunayo',
    position: 'Editor | Colourist | Sound',
  },
  {
    id: 19,
    link: 'https://youtu.be/egCBNfstFbg?si=3Zq-IheS7Frf87pQ',
    title: 'The Art Of Letting Go',
    name: 'David Odunayo',
    position: 'Editor | Colourist | Sound',
  },
  {
    id: 20,
    link: 'https://www.youtube.com/watch?v=HN-X5xCbNTw&t=631s',
    title: 'Imperfect Match 2',
    name: 'David Odunayo',
    position: 'Editor | Colourist | Sound',
  },
  {
    id: 21,
    link: 'https://youtu.be/1K9vYmaA2_k?si=hEA0JcUgHAv5if2n',
    title: 'In My Shoes',
    name: 'David Odunayo',
    position: 'Editor | Colourist | Sound',
  },
  {
    id: 22,
    link: 'https://www.youtube.com/watch?v=2RMGhCWuF-I',
    title: 'Imperfect Match',
    name: 'David Odunayo',
    position: 'Editor | Colourist | Sound',
  },
  {
    id: 23,
    link: 'https://www.youtube.com/watch?v=B2cRLdBSSjI',
    title: 'Built To Last',
    name: 'David Odunayo',
    position: 'Editor | Colourist | Sound',
  },
  {
    id: 24,
    link: 'https://www.youtube.com/watch?v=8b1nqHhOwHU&t=3415s',
    title: 'A Christmas Gift',
    name: 'David Odunayo',
    position: 'Editor | Colourist | Sound',
  },
  {
    id: 25,
    link: 'https://youtu.be/B5z2MfBsCjw?si=z7uSpfuX26vAk_-E',
    title: 'Keep It Moving',
    name: 'David Odunayo',
    position: 'Editor | Colourist | Sound',
  },
  {
    id: 26,
    link: 'https://youtu.be/Y5BvGfEv4wc?si=cNZXvYf5-drpkKEN',
    title: 'Mo Fe Were Part 1',
    name: 'David Odunayo',
    position: ' Sound',
  },
];
