export const data = [
  {
    id: 1,
    link: 'https://www.youtube.com/watch?v=pTAheLPUWlw',
    title: 'Summer Rain Official Trailer',
    name: 'David Odunayo',
    position: 'Editor | Colourist | Sound',
    description:
      '10 years is a long time to love someone. Will Murewa Abe and Admichi Amadi make it? ',
    Synopsis:
      'A story of love, perseverance, hope and second chance; Summer Rain is in cinemas nationwide, starting FEBRUARY 7, don’t miss it!',
    comment1: '',
    user1: '',
    comment2: '',
    user2: '',
    comment3: '',
    user3: '',
    comment4: '',
    user4: '',
    comment5: '',
    user5: '',
    comment6: '',
    user6: '',
    comment7: '',
    user7: '',
  },
  {
    id: 2,
    link: 'https://www.youtube.com/watch?v=56ma3dYVfM0&t=2171s',
    title: 'Beneath The Facade',
    name: 'David Odunayo',
    position: 'Editor | Colourist | Sound',
    comment1: '',
    user1: '',
    comment2: '',
    user2: '',
    comment3: '',
    user3: '',
    comment4: '',
    user4: '',
    comment5: '',
    user5: '',
    comment6: '',
    user6: '',
    comment7: '',
    user7: '',
  },

  {
    id: 3,
    link: 'https://youtu.be/egCBNfstFbg?si=3Zq-IheS7Frf87pQ',
    title: 'The Art Of Letting Go',
    name: 'David Odunayo',
    position: 'Editor | Colourist | Sound',
    comment1: '',
    user1: '',
    comment2: '',
    user2: '',
    comment3: '',
    user3: '',
    comment4: '',
    user4: '',
    comment5: '',
    user5: '',
    comment6: '',
    user6: '',
    comment7: '',
    user7: '',
  },

  {
    id: 4,
    link: 'https://youtu.be/CR9Ndm6W50g?si=7l-3ZNZEIJDQ8M0E',
    title: 'Heart Over Time',
    name: 'David Odunayo',
    position: 'Editor | Colourist | Sound',
    description: '',
    Synopsis: '',
    comment1: 'Always delivering top-quality content! Love it!',
    user1: 'InspiredSoul',
    comment2: 'Your growth and progress are inspiring',
    user2: 'AlexinMotion',
    comment3: 'Every time you create, its a masterpiece',
    user3: 'TrailbiazerX',
    comment4: 'you are bringing something fresh to the game!',
    user4: 'StarGazer99',
    comment5: 'Your work speaks volumes! Keep going!',
    user5: 'ImpactMaker',
    comment6: 'This is so insightful and well-done!',
    user6: 'AlwaysLearning',
    comment7: 'You have a way of making things extraordinary!',
    user7: 'TheBrightOne',
  },
  {
    id: 5,
    link: 'https://youtu.be/wusI_-WUjd4?si=B0sDu1rydxKVU4k4',
    title: 'No Love Lust',
    name: 'David Odunayo',
    position: 'Editor | Colourist | Sound',
    description: '',
    Synopsis: '',
    comment1: 'Pure genius! your talent knows no bounds!',
    user1: 'FearlessCreator',
    comment2: 'This is the kind of content the world needs more of!',
    user2: 'UnstoppableU',
    comment3: 'This is simply amazing! Your creativity shines through!',
    user3: 'PowerMind99',
    comment4: 'Your work is a breath of fresh air. So inspiring',
    user4: 'TheCreativeSoul',
    comment5: 'The level of details in this in incredible! Bravo!',
    user5: 'EliteVisionary',
    comment6: 'This is next-level talent! You are unstoppable',
    user6: 'FutureMogul',
    comment7: 'Your passion is truly reflected in this! Love it!',
    user7: 'Game Changer',
  },

  {
    id: 6,
    link: 'https://www.youtube.com/watch?v=kHHCzyqdoNU',
    title: 'Blind Fury',
    name: 'David Odunayo',
    position: 'Editor | Colourist | Sound',
    description:
      'Blind Fury is a beautiful movie that speaks to love, forgiveness, family life and therapy.',
    Synopsis: '',
    comment1: '',
    user1: '',
    comment2: '',
    user2: '',
    comment3: '',
    user3: '',
    comment4: '',
    user4: '',
    comment5: '',
    user5: '',
    comment6: '',
    user6: '',
    comment7: '',
    user7: '',
  },
  {
    id: 7,
    link: 'https://www.youtube.com/watch?v=ldOE2aOof58&t=3756s',
    title: 'Sweet Vengeance',
    name: 'David Odunayo',
    position: 'Editor | Colourist | Sound',
    description:
      'This amazing masterpiece will keep you glued to your screen... very educative and captivating',
    Synopsis: '',
    comment1: '',
    user1: '',
    comment2: '',
    user2: '',
    comment3: '',
    user3: '',
    comment4: '',
    user4: '',
    comment5: '',
    user5: '',
    comment6: '',
    user6: '',
    comment7: '',
    user7: '',
  },
  {
    id: 8,
    link: 'https://www.youtube.com/watch?v=6H0Q9QDKRcM',
    title: 'Love In Progress',
    name: 'David Odunayo',
    position: 'Editor | Colourist | Sound',
    description:
      "LOVE IN PROGRESS is a Romantic Nigerian Movie you don't want to miss. If you're searching for Nigerian Movies 2024 Latest Full Movies, this is for you. Watch the Latest Nollywood Movies 2024 (Full Movie). This is a free movie starring the best actors e.g Ayo Adesanya, Bobby Ekpe, Bryan Okoye, Darasimi Ogbetah. Don't miss this week's new release of the Latest Nigerian Movies.",
    Synopsis:
      "Iye enters an arranged relationship with Osi. However, their budding romance is threatened when she meets and befriends Osagie, Osi's cousin.",
    comment1: 'This is absolutely brilliant! your work keeps getting better',
    user1: 'TechGuru99',
    comment2: 'Such an inspiring piece! Keep up the amazing work!',
    user2: 'SarahCreates',
    comment3: 'Your attention to details is next-Level. Truly impressive!',
    user3: 'MasterX',
    comment4: 'This is pure creativity at its finest! Well done.',
    user4: 'LunaWrites',
    comment5: 'I love the way you bring ideas to life. Incredible!',
    user5: 'VisualAce',
    comment6: 'You nailed it! The execution is flawless',
    user6: 'Maverick101',
    comment7: 'Such a fresh perspective! Always excited to see your work!',
    user7: 'Simply Emma',
  },
  {
    id: 9,
    link: 'https://www.youtube.com/watch?v=NgrN9chjLwo',
    title: 'Official Trailer Of Sisters by Chance',
    name: 'David Odunayo',
    position: 'Editor | Colourist | Sound',
    description: '',
    Synopsis: '',
    comment1: '',
    user1: '',
    comment2: '',
    user2: '',
    comment3: '',
    user3: '',
    comment4: '',
    user4: '',
    comment5: '',
    user5: '',
    comment6: '',
    user6: '',
    comment7: '',
    user7: '',
  },
  {
    id: 10,
    link: 'https://www.youtube.com/watch?v=g23mrltsSX4',
    title: 'She ToMy Official Trailer',
    name: 'David Odunayo',
    position: 'Editor',
    description: '',
    Synopsis: '',
    comment1: '',
    user1: '',
    comment2: '',
    user2: '',
    comment3: '',
    user3: '',
    comment4: '',
    user4: '',
    comment5: '',
    user5: '',
    comment6: '',
    user6: '',
    comment7: '',
    user7: '',
  },
  {
    id: 10,
    link: 'https://www.youtube.com/watch?v=2tfZEPfnMLI',
    title: 'Trailer of Feeling Butterflies',
    name: 'David Odunayo',
    position: 'Editor | Colourist | Sound',
    comment1: '',
    user1: '',
    comment2: '',
    user2: '',
    comment3: '',
    user3: '',
    comment4: '',
    user4: '',
    comment5: '',
    user5: '',
    comment6: '',
    user6: '',
    comment7: '',
    user7: '',
  },
  {
    id: 11,
    link: 'https://www.youtube.com/watch?v=E1hBB_hA_w8',
    title: 'Trailer of the movie The Kids And The Babysitter',
    name: 'David Odunayo',
    position: 'Editor | Colourist | Sound',
    comment1: '',
    user1: '',
    comment2: '',
    user2: '',
    comment3: '',
    user3: '',
    comment4: '',
    user4: '',
    comment5: '',
    user5: '',
    comment6: '',
    user6: '',
    comment7: '',
    user7: '',
  },
  {
    id: 12,
    link: 'https://www.youtube.com/watch?v=V335_JIzhEU',
    title: 'Two Heartbeats Trailer',
    name: 'David Odunayo',
    position: 'Colourist',
    comment1: '',
    user1: '',
    comment2: '',
    user2: '',
    comment3: '',
    user3: '',
    comment4: '',
    user4: '',
    comment5: '',
    user5: '',
    comment6: '',
    user6: '',
    comment7: '',
    user7: '',
  },
  {
    id: 13,
    link: 'https://www.youtube.com/watch?v=UYsseEOZuDc',
    title: 'Trailer of A Not So Perfect Family',
    name: 'David Odunayo',
    position: 'Editor | Colourist | Sound',
    comment1: '',
    user1: '',
    comment2: '',
    user2: '',
    comment3: '',
    user3: '',
    comment4: '',
    user4: '',
    comment5: '',
    user5: '',
    comment6: '',
    user6: '',
    comment7: '',
    user7: '',
  },
  {
    id: 14,
    link: 'https://www.youtube.com/watch?v=53V3tzH1a-M',
    title: 'Trailer of When Hearts Collide',
    name: 'David Odunayo',
    position: 'Trailer | Colourist | Sound',
    comment1: '',
    user1: '',
    comment2: '',
    user2: '',
    comment3: '',
    user3: '',
    comment4: '',
    user4: '',
    comment5: '',
    user5: '',
    comment6: '',
    user6: '',
    comment7: '',
    user7: '',
  },
  {
    id: 15,
    link: 'https://www.youtube.com/watch?v=kLp6GsmL7fk',
    title: 'Trailer of Moment of Truth',
    name: 'David Odunayo',
    position: 'Editor | Colourist | Sound',
    comment1: '',
    user1: '',
    comment2: '',
    user2: '',
    comment3: '',
    user3: '',
    comment4: '',
    user4: '',
    comment5: '',
    user5: '',
    comment6: '',
    user6: '',
    comment7: '',
    user7: '',
  },
  {
    id: 16,
    link: 'https://youtu.be/HN-X5xCbNTw?si=V4lpJcQwgkaJWuxh',
    title: 'IMPERFECT MATCH',
    name: 'David Odunayo',
    position: 'Editor | Colourist | Sound',
    description: '',
    Synopsis: '',
    comment1: 'Mind-blowing! Your skills are top-tier ',
    user1: 'King Of Ideas',
    comment2: 'Everytime i see your work, i get inspired! Keep shining',
    user2: 'JaneDoe_Artist',
    comment3: 'This is exactly what i needed today. Thank you!',
    user3: 'TheRealMark',
    comment4: 'Your dedication and talent are so evident here. Amazing job!',
    user4: 'BoldVisionary',
    comment5: 'Your craftsmanship is beyond words. So well done!',
    user5: 'PixelPerfect',
    comment6: 'You are setting the bar so high! Absolute excellence!',
    user6: 'FutureLegend',
    comment7: "i'm always learning something new from your work",
    user7: 'EveTheExplorer',
  },
  {
    id: 17,
    link: 'https://www.youtube.com/watch?v=D-tudHqBPH0&t=4497s',
    title: 'Brotherly Love',
    name: 'David Odunayo',
    position: 'Editor | Colourist | Sound',
    comment1: '',
    user1: '',
    comment2: '',
    user2: '',
    comment3: '',
    user3: '',
    comment4: '',
    user4: '',
    comment5: '',
    user5: '',
    comment6: '',
    user6: '',
    comment7: '',
    user7: '',
  },
  {
    id: 18,
    link: 'https://www.youtube.com/watch?v=GoWZfsdd1yw&t=5090s',
    title: 'Th Beauty of Things',
    name: 'David Odunayo',
    position: 'Editor | Colourist | Sound',
    comment1: '',
    user1: '',
    comment2: '',
    user2: '',
    comment3: '',
    user3: '',
    comment4: '',
    user4: '',
    comment5: '',
    user5: '',
    comment6: '',
    user6: '',
    comment7: '',
    user7: '',
  },
  {
    id: 19,
    link: 'https://www.youtube.com/watch?v=yLGlclnGJBo',
    title: 'MOMENTS OF TRUTH',
    name: 'David Odunayo',
    position: 'Editor | Colourist | Sound',
    description:
      "In an elite high school, Malik, a popular and charismatic student, is found dead in a bathroom, sending shockwaves through the students and staff. Struggling with grief and seeking answers, Malik’s mother hires a determined private detective to uncover the truth behind her son's mysterious death. The detective’s investigation reveals a web of secrets and lies within the school. Students are questioned, and suspicions arise when a new girl is found with Malik's phone. As the detective digs deeper, a dark world of illegal drug trafficking emerges. Malik was caught in this dangerous web, and the investigation reveals that he was being supplied by a clandestine drug ring. The shocking climax uncovers that Malik’s life was taken due to unpaid debts by the leader of this drug ring who is someone everybody would least expect.",
    Synopsis: '',
    comment1: 'This is a masterpiece keep pushing boundaries',
    user1: 'DynamicDan',
    comment2: 'Such positive energy in your work! Love it!',
    user2: 'GlowGetter',
    comment3: 'You have a unique touch that stands out!',
    user3: 'NextGenMind',
    comment4: 'Creativity at its peak! So impressive!',
    user4: 'SkyHighDreamer',
    comment5: 'You make it look so easy, yet so powerful!',
    user5: 'Epicinnovator',
    comment6: 'This just made my day! Keep shining!',
    user6: 'VisionUnlocked',
    comment7: 'You are on another level! Absolute fire!',
    user7: 'TheRealGoat',
  },
  {
    id: 20,
    link: 'https://www.youtube.com/watch?v=HN-X5xCbNTw&t=631s',
    title: 'Imperfect Match 2',
    name: 'David Odunayo',
    position: 'Editor | Colourist | Sound',
    comment1: '',
    user1: '',
    comment2: '',
    user2: '',
    comment3: '',
    user3: '',
    comment4: '',
    user4: '',
    comment5: '',
    user5: '',
    comment6: '',
    user6: '',
    comment7: '',
    user7: '',
  },
  {
    id: 21,
    link: 'https://youtu.be/1K9vYmaA2_k?si=hEA0JcUgHAv5if2n',
    title: 'In My Shoes',
    name: 'David Odunayo',
    position: 'Editor | Colourist | Sound',
    comment1: '',
    user1: '',
    comment2: '',
    user2: '',
    comment3: '',
    user3: '',
    comment4: '',
    user4: '',
    comment5: '',
    user5: '',
    comment6: '',
    user6: '',
    comment7: '',
    user7: '',
  },
  {
    id: 22,
    link: 'https://www.youtube.com/watch?v=2RMGhCWuF-I',
    title: 'Imperfect Match',
    name: 'David Odunayo',
    position: 'Editor | Colourist | Sound',
    comment1: '',
    user1: '',
    comment2: '',
    user2: '',
    comment3: '',
    user3: '',
    comment4: '',
    user4: '',
    comment5: '',
    user5: '',
    comment6: '',
    user6: '',
    comment7: '',
    user7: '',
  },
  {
    id: 23,
    link: 'https://www.youtube.com/watch?v=B2cRLdBSSjI',
    title: 'Built To Last',
    name: 'David Odunayo',
    position: 'Editor | Colourist | Sound',
    comment1: '',
    user1: '',
    comment2: '',
    user2: '',
    comment3: '',
    user3: '',
    comment4: '',
    user4: '',
    comment5: '',
    user5: '',
    comment6: '',
    user6: '',
    comment7: '',
    user7: '',
  },
  {
    id: 24,
    link: 'https://www.youtube.com/watch?v=8b1nqHhOwHU&t=3415s',
    title: 'A Christmas Gift',
    name: 'David Odunayo',
    position: 'Editor | Colourist | Sound',
    comment1: '',
    user1: '',
    comment2: '',
    user2: '',
    comment3: '',
    user3: '',
    comment4: '',
    user4: '',
    comment5: '',
    user5: '',
    comment6: '',
    user6: '',
    comment7: '',
    user7: '',
  },
  {
    id: 25,
    link: 'https://youtu.be/B5z2MfBsCjw?si=z7uSpfuX26vAk_-E',
    title: 'Keep It Moving',
    name: 'David Odunayo',
    position: 'Editor | Colourist | Sound',
    comment1: '',
    user1: '',
    comment2: '',
    user2: '',
    comment3: '',
    user3: '',
    comment4: '',
    user4: '',
    comment5: '',
    user5: '',
    comment6: '',
    user6: '',
    comment7: '',
    user7: '',
  },
  {
    id: 26,
    link: 'https://youtu.be/Y5BvGfEv4wc?si=cNZXvYf5-drpkKEN',
    title: 'Mo Fe Were Part 1',
    name: 'David Odunayo',
    position: ' Sound',
    comment1: '',
    user1: '',
    comment2: '',
    user2: '',
    comment3: '',
    user3: '',
    comment4: '',
    user4: '',
    comment5: '',
    user5: '',
    comment6: '',
    user6: '',
    comment7: '',
    user7: '',
  },
  {
    id: 27,
    link: 'https://www.youtube.com/results?search_query=illusion+of+us+uchenna+mbunabo+tv',
    title: 'Illusions of Us',
    name: 'David Odunayo',
    position: 'Editor | Colourist | Sound',
    comment1: '',
    user1: '',
    comment2: '',
    user2: '',
    comment3: '',
    user3: '',
    comment4: '',
    user4: '',
    comment5: '',
    user5: '',
    comment6: '',
    user6: '',
    comment7: '',
    user7: '',
  },
  {
    id: 28,
    link: 'https://www.youtube.com/watch?v=KsFceULYrWY&list=PLcioA4KXOStvKsrb3vBZYyYf4QSHUQLX6',
    title: 'Omo Momizs Full Series',
    name: 'David Odunayo',
    position: 'Editor | Cinematographer',
    comment1: '',
    user1: '',
    comment2: '',
    user2: '',
    comment3: '',
    user3: '',
    comment4: '',
    user4: '',
    comment5: '',
    user5: '',
    comment6: '',
    user6: '',
    comment7: '',
    user7: '',
  },
  {
    id: 29,
    link: 'https://www.youtube.com/watch?v=Vq2ZfYeHOik',
    title: 'Nu season!! Picture Perfect Series Trailer',
    name: 'David Odunayo',
    position: 'Editor | Colourist | Sound',
    comment1: '',
    user1: '',
    comment2: '',
    user2: '',
    comment3: '',
    user3: '',
    comment4: '',
    user4: '',
    comment5: '',
    user5: '',
    comment6: '',
    user6: '',
    comment7: '',
    user7: '',
  },
  {
    id: 30,
    link: 'https://www.youtube.com/watch?v=hHYI-rOW9EQ&t=2811s',
    title: 'Lost In Lagos',
    name: 'David Odunayo',
    position: 'Editor | Colourist | Sound',
    comment1: '',
    user1: '',
    comment2: '',
    user2: '',
    comment3: '',
    user3: '',
    comment4: '',
    user4: '',
    comment5: '',
    user5: '',
    comment6: '',
    user6: '',
    comment7: '',
    user7: '',
  },
  {
    id: 31,
    link: 'https://www.youtube.com/watch?v=t3MnaJJgZuE&t=4056s',
    title: 'Strange Affections',
    name: 'David Odunayo',
    position: 'Editor | Colourist | Sound',
    comment1: '',
    user1: '',
    comment2: '',
    user2: '',
    comment3: '',
    user3: '',
    comment4: '',
    user4: '',
    comment5: '',
    user5: '',
    comment6: '',
    user6: '',
    comment7: '',
    user7: '',
  },
  {
    id: 32,
    link: 'https://www.youtube.com/watch?v=WgxJKD2iV8E',
    title: '30 FOR 30',
    name: 'David Odunayo',
    position: 'Editor | Colourist | Sound',
    comment1: '',
    user1: '',
    comment2: '',
    user2: '',
    comment3: '',
    user3: '',
    comment4: '',
    user4: '',
    comment5: '',
    user5: '',
    comment6: '',
    user6: '',
    comment7: '',
    user7: '',
  },
  {
    id: 33,
    link: 'https://www.youtube.com/watch?v=WJpOD8Q0fN8&t=4164s',
    title: 'Dare To Love',
    name: 'David Odunayo',
    position: 'Editor | Colourist | Sound',
    comment1: '',
    user1: '',
    comment2: '',
    user2: '',
    comment3: '',
    user3: '',
    comment4: '',
    user4: '',
    comment5: '',
    user5: '',
    comment6: '',
    user6: '',
    comment7: '',
    user7: '',
  },
  {
    id: 34,
    link: 'https://www.youtube.com/watch?v=YFbNAoEUHbI',
    title: 'Healed Hearts',
    name: 'David Odunayo',
    position: 'Editor | Colourist | Sound',
    comment1: '',
    user1: '',
    comment2: '',
    user2: '',
    comment3: '',
    user3: '',
    comment4: '',
    user4: '',
    comment5: '',
    user5: '',
    comment6: '',
    user6: '',
    comment7: '',
    user7: '',
  },
  {
    id: 35,
    link: 'https://youtu.be/JzC2bYCV6Jw?si=AygIYmONfu7IlF-l',
    title: 'Dear Diane',
    name: 'David Odunayo',
    position: 'Editor | Colourist | Sound',
    description:
      "You know the butterflies we feel when we meet someone who we believe will change our lives for the better? It's like they add color to your life, and that's what this episode feels like. I hope you meet people who bring a smile to your face from the first hello to the last goodbye.",
    Synopsis: '',
    comment1: '',
    user1: '',
    comment2: '',
    user2: '',
    comment3: '',
    user3: '',
    comment4: '',
    user4: '',
    comment5: '',
    user5: '',
    comment6: '',
    user6: '',
    comment7: '',
    user7: '',
  },
];
